In [3]:
import torch
model = torch.hub.load("gmberton/eigenplaces", "get_trained_model", backbone="ResNet50", fc_output_dim=2048)

Downloading: "https://github.com/gmberton/eigenplaces/zipball/main" to /Users/jettchen/.cache/torch/hub/main.zip


Returning EigenPlaces model with backbone: ResNet50 with features dimension 2048


/opt/homebrew/Caskroom/miniforge/base/envs/geoloc/lib/python3.11/site-packages/torch/hub.py:294: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/gmberton/cosplace/zipball/main" to /Users/jettchen/.cache/torch/hub/main.zip


Returning CosPlace model with backbone: ResNet50 with features dimension 512


Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /Users/jettchen/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth
100%|██████████| 97.8M/97.8M [00:06<00:00, 16.1MB/s]
Downloading: "https://github.com/gmberton/CosPlace/releases/download/v1.0/ResNet50_512_cosplace.pth" to /Users/jettchen/.cache/torch/hub/checkpoints/ResNet50_512_cosplace.pth
100%|██████████| 94.0M/94.0M [00:04<00:00, 20.1MB/s]
Downloading: "https://github.com/gmberton/EigenPlaces/releases/download/v1.0/ResNet50_2048_eigenplaces.pth" to /Users/jettchen/.cache/torch/hub/checkpoints/ResNet50_2048_eigenplaces.pth
100%|██████████| 106M/106M [00:05<00:00, 22.2MB/s] 


In [4]:
model

GeoLocalizationNet_(
  (backbone): Sequential(
    (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (4): Sequential(
      (0): Bottleneck(
        (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (downsample): Sequential(
          (0)

In [11]:
input_size = (1, 3, 512, 512) 
input_tensor = torch.randn(input_size)
output = model(input_tensor)

In [12]:
output

tensor([[-0.0317, -0.0304,  0.0111,  ...,  0.0114,  0.0313,  0.0026]],
       grad_fn=<DivBackward0>)

In [14]:
output.shape

torch.Size([1, 2048])

In [13]:
%%time
model(input_tensor)

CPU times: user 366 ms, sys: 281 ms, total: 648 ms
Wall time: 601 ms


tensor([[-0.0317, -0.0304,  0.0111,  ...,  0.0114,  0.0313,  0.0026]],
       grad_fn=<DivBackward0>)

In [15]:
from inference import weight_im
from PIL import Image

In [17]:
weight_im(Image.open('../../images/NY5.png').convert('RGB'))

tensor([[ 0.0372,  0.0098,  0.0095,  ..., -0.0025, -0.0281, -0.0351]],
       grad_fn=<DivBackward0>)